### PR TITLE
Asist eval

### PR DESCRIPTION
**Pull request by paulosoaresua**
@adarshp,

I think I finished the automation process for the ASIST evaluation. I would like you to take a look and see if anything needs to be changed.

I added a few more exclusions to the gsutil command so that only trial messages files are synchronized. I also added a few more commands after the synchronization to create a directory (study-1_2020.08_split) where the symlinks will be put during the data splitting. A file called eval_list.txt is also created in the new directory where we should inform the list of filenames we want to use for evaluation. File extensions should be omitted as now we have both .metadata and .fov files with the same name.

In the first time you run in your machine, just do "make sync". This will synchronize the data and create the directory and file I mentioned above. Then pick some filenames from the files downloaded to be your evaluation data, and add them to the eval_list.txt file. Next, you can run make with all the targets.

In the subsequent executions you can run make normally to execute all the targets because the eval_list.txt will already be filled. The message conversion process only converts new messages, so it shouldn't take long after the first time. You'll notice that along with the files of matrices of observations generated by this process, there's a file called metadata.json. This file stores the list of messages processed: successfully or unsuccessfully and the corresponding error. The converter uses this list to skip messages already converted, and only appends new data to the matrices.

The makefile proceeds by training the model, evaluating it (this step runs sum-product to compute the estimates), and generating the final report in the same folder where the evaluations were saved in the end of the previous step.      

In sum, when you run for the first time do:
1. make sync
2. Add some filenames (without extension) to the file data/asist/study-1_2020.08_split/eval_list.txt
3. make (this will sync again but there should be nothing more to download)

In the subsequent executions you can just do:
1. make 

The subsequent executions will serve to retrain the model with more data in case there's more available. However, this won't change the accuracy much as our model is still too simple to understand complex relationships between the entities defined.

### CODE REVIEW

**Review by adarshp — CHANGES_REQUESTED** [review]
Hi @paulosoaresua , 

A few comments:

- First, a couple of style issues - 
  - Can you try to wrap long lines in the Makefile so that the line width doesn't exceed 80 (with the exception of long URLs - you can leave them as is)
  - Similarly, try avoiding long lines in the Python code. I haven't used the feature, but I believe that PyCharm can automatically reformat your Python code to conform to PEP8: https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html. This might work on the Makefiles too, but I don't know for sure.
- I think the additional code in `tools/sync_asist_data` to create the split directory should be moved into `tools/split_data` - it seems a bit more appropriate.
- Similar to Falcon_v1.0.json, the file `eval_list.txt` should be assumed to exist, rather than created on the fly - it should also be listed as a prererequisite for one of the targets - so that if `eval_list.txt` is changed, the appropriate parts of the pipeline will be re-run.
- Also, `tools/create_asist_report.py`, `$(EVAL_DIR)/evaluations.json`, `$(EVAL_SAMPLES_DIR)/metadata.json`, and `$(EVAL_DIR)/report.txt
` (and maybe `$(HORIZON)`) should be prerequisites for the `report` target in the Makefile, since we want the report to be regenerated if any of these are changed. As a rule of thumb, the things in the recipe that can potentially change should be listed as prerequisites for the target. In the case of Python scripts, if you have one that takes a number of command line arguments, you can achieve some brevity with the Make special variables `$^` and `$@` (See https://github.com/ml4ai/delphi/blob/ce280d67f28e5884632e4a3ddd7ac366f5ad6d2c/scripts/Makefile#L71-L72 for an example, and https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html for a reference).
- `report` should probably not be a phony target, but an actual filename (or `$(EVAL_DIR)/report.txt`) since there is a concrete file produced by that recipe. As a rule of thumb, if you are not calling out to other 'Make' type utilities for incremental rebuilding (i.e. `gsutil`, `rsync`, or existing Makefiles in other directories), and the recipe is producing a single tangible file as the output, the target of the recipe should not be phony.

Finally, I am getting an error when I try to run the pipeline:

```
(tomcat) ~/git/ml4ai/tomcat-tmm (asist_eval) $ make

./tools/sync_asist_data
Building synchronization state...
Starting synchronization...
Please, update /Users/adarsh/git/ml4ai/tomcat-tmm/data/asist/study-1_2020.08_split/eval_list.txt accordingly.

./tools/split_data
make: *** [split] Error 1
```

I've placed the Falcon map in the correct place:
```
(tomcat) ~/git/ml4ai/tomcat-tmm (asist_eval) $ ls data/maps/asist/
Falcon_v1.0.json
```

and here's the contents of my `eval_list.txt`:

```
(tomcat) ~/git/ml4ai/tomcat-tmm (asist_eval) $ cat data/asist/study-1_2020.08_split/eval_list.txt
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-120_Team-na_Member-51_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-123_Team-na_Member-52_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-128_Team-na_Member-54_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-130_Team-na_Member-55_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-145_Team-na_Member-60_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-180_Team-na_Member-71_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-182_Team-na_Member-72_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-188_Team-na_Member-74_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-199_Team-na_Member-78_Vers-1
/Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-232_Team-na_Member-89_Vers-1
```

Are you able to reproduce this error? Am I missing something?

**Comment by paulosoaresua** [comment]
> Hi @paulosoaresua ,
> 
> A few comments:
> 
> * First, a couple of style issues -
>   
>   * Can you try to wrap long lines in the Makefile so that the line width doesn't exceed 80 (with the exception of long URLs - you can leave them as is)
>   * Similarly, try avoiding long lines in the Python code. I haven't used the feature, but I believe that PyCharm can automatically reformat your Python code to conform to PEP8: https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html. This might work on the Makefiles too, but I don't know for sure.
> * I think the additional code in `tools/sync_asist_data` to create the split directory should be moved into `tools/split_data` - it seems a bit more appropriate.
> * Similar to Falcon_v1.0.json, the file `eval_list.txt` should be assumed to exist, rather than created on the fly - it should also be listed as a prererequisite for one of the targets - so that if `eval_list.txt` is changed, the appropriate parts of the pipeline will be re-run.
> * Also, `tools/create_asist_report.py`, `$(EVAL_DIR)/evaluations.json`, `$(EVAL_SAMPLES_DIR)/metadata.json`, and `$(EVAL_DIR)/report.txt ` (and maybe `$(HORIZON)`) should be prerequisites for the `report` target in the Makefile, since we want the report to be regenerated if any of these are changed. As a rule of thumb, the things in the recipe that can potentially change should be listed as prerequisites for the target. In the case of Python scripts, if you have one that takes a number of command line arguments, you can achieve some brevity with the Make special variables `$^` and `$@` (See https://github.com/ml4ai/delphi/blob/ce280d67f28e5884632e4a3ddd7ac366f5ad6d2c/scripts/Makefile#L71-L72 for an example, and https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html for a reference).
> * `report` should probably not be a phony target, but an actual filename (or `$(EVAL_DIR)/report.txt`) since there is a concrete file produced by that recipe. As a rule of thumb, if you are not calling out to other 'Make' type utilities for incremental rebuilding (i.e. `gsutil`, `rsync`, or existing Makefiles in other directories), and the recipe is producing a single tangible file as the output, the target of the recipe should not be phony.
> 
> Finally, I am getting an error when I try to run the pipeline:
> 
> ```
> (tomcat) ~/git/ml4ai/tomcat-tmm (asist_eval) $ make
> 
> ./tools/sync_asist_data
> Building synchronization state...
> Starting synchronization...
> Please, update /Users/adarsh/git/ml4ai/tomcat-tmm/data/asist/study-1_2020.08_split/eval_list.txt accordingly.
> 
> ./tools/split_data
> make: *** [split] Error 1
> ```
> 
> I've placed the Falcon map in the correct place:
> 
> ```
> (tomcat) ~/git/ml4ai/tomcat-tmm (asist_eval) $ ls data/maps/asist/
> Falcon_v1.0.json
> ```
> 
> and here's the contents of my `eval_list.txt`:
> 
> ```
> (tomcat) ~/git/ml4ai/tomcat-tmm (asist_eval) $ cat data/asist/study-1_2020.08_split/eval_list.txt
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-120_Team-na_Member-51_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-123_Team-na_Member-52_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-128_Team-na_Member-54_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-130_Team-na_Member-55_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-145_Team-na_Member-60_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-180_Team-na_Member-71_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-182_Team-na_Member-72_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-188_Team-na_Member-74_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-199_Team-na_Member-78_Vers-1
> /Users/adarsh/git/ml4ai/tomcat-tmm/data/study-1_2020.08/HSRData_TrialMessages_CondBtwn-NoTriageNoSignal_CondWin-FalconEasy-StaticMap_Trial-232_Team-na_Member-89_Vers-1
> ```
> 
> Are you able to reproduce this error? Am I missing something?

Yes. Remove the path from the filenames in eval_list.txt. I'll fix it to just ignore when a file is not found. 

Also, I thought of creating the split folder inside the split_data script, but this script assumes this folder already exists as well as the file eval_list.txt. So it has to be called before the split_data target. That's why I moved to the sync_data. Because after sync we would just need to fill the eval_list.txt file. Should we let the user create the folder and the file manually then?

**Comment by adarshp** [comment]
@paulosoaresua - after removing the full path, I'm able to run the pipeline. Re: your question about the eval_list.txt and the split folder - yes, we should let the user create the folder and file manually, but make sure to add those instructions as comments in the Makefile.

**Comment by adarshp** [comment]
I'll go ahead and merge this PR since I'm able to run the pipeline - you can make the changes in the review in the next PR. Thanks!

**Pull request merged**
